### ISSUE TITLE
Missing distanceAccuracy in RunwayDeclaredDistanceValue

### ISSUE THREAD

**Issue by andreeaperca** [aixm/donlon#1]
In file EA_AIP_DS_FULL_20170701.xml 

RunwayDeclaredDistanceValue / distanceAccuracy is missing for all associatedDeclaredDistance. 

According to Runway - AIXM Coding Checklist it is mandatory.  [https://ext.eurocontrol.int/aixm_confluence/display/ACGAIP/Runway+-+AIXM+Coding+Checklist]

**Comment by wolfi2909** [comment]
all missing elements added.
