### ISSUE TITLE
Two different NDB with the same gml:pos

### ISSUE THREAD

**Issue by antoniolocandro** [aixm/donlon#11]
Although the dataset is a sample one it is highly unlikely that at the same coordinates you would have 2 different NDB antennas

**2d2c95dc-cfec-4eae-96ca-dc95fff03757**
<aixm:type>NDB</aixm:type>
					<aixm:designator>ROK</aixm:designator>
					<aixm:name>ROCKBY</aixm:name>
					<aixm:navaidEquipment>
						<aixm:NavaidComponent gml:id="N-KL411">
							<aixm:theNavaidEquipment
								xlink:href="urn:uuid:04e56175-c5f3-492d-a453-f4cfdad94e6a"
								xlink:title="NDB_ROK"/>
						</aixm:NavaidComponent>
					</aixm:navaidEquipment>
					<aixm:location>
						<aixm:ElevatedPoint srsName="urn:ogc:def:crs:EPSG::4326" gml:id="navelKL11">
							<gml:pos>51.983333 -32.55</gml:pos>
							<aixm:horizontalAccuracy uom="M">100</aixm:horizontalAccuracy>
						</aixm:ElevatedPoint>
					</aixm:location>

**2d2c95dc-cfec-4eae-96ca-dc95fff03756**
<aixm:type>NDB</aixm:type>
					<aixm:designator>ROB</aixm:designator>
					<aixm:name>ROBINE</aixm:name>
					<aixm:navaidEquipment>
						<aixm:NavaidComponent gml:id="N-KL41">
							<aixm:theNavaidEquipment
								xlink:href="urn:uuid:04e56175-c5f3-492d-a453-f4cfdad94e6f"
								xlink:title="NDB_ROB"/>
						</aixm:NavaidComponent>
					</aixm:navaidEquipment>
					<aixm:location>
						<aixm:ElevatedPoint srsName="urn:ogc:def:crs:EPSG::4326" gml:id="navelKL1">
							<gml:pos>51.983333 -32.55</gml:pos>
							<aixm:horizontalAccuracy uom="M">100</aixm:horizontalAccuracy>
						</aixm:ElevatedPoint>
					</aixm:location>

**Comment by porosnie** [comment]
Corrected
