### ISSUE TITLE
Length of Route Segment incorrect

### ISSUE THREAD

**Issue by antoniolocandro** [aixm/donlon#6]
The coded length of the route segment doesn't match the length that I calculate using the start/end points

See the following example:

<aixm:RouteSegment gml:id="uuid.cc9c7cc4-e000-4741-854d-b7d93973e099">

<aixm:magneticTrack>74.0</aixm:magneticTrack>
					<aixm:reverseMagneticTrack>254.0</aixm:reverseMagneticTrack>
					<aixm:length uom="KM">69.3</aixm:length>

<aixm:Curve srsName="urn:ogc:def:crs:EPSG::4326" gml:id="crv2110">
							<gml:segments>
								<gml:GeodesicString>
									<gml:posList>42.5016666666667 -37.0016666666667 42.675
										-36.1733333333333</gml:posList>
								</gml:GeodesicString>
							</gml:segments>
						</aixm:Curve>

With those pos the Distance should be 70.67 NM instead of the 69.3 NM provided in the example

The positions would be 
start = 423006N 0370006W
end = 424030N 0361024W
forward_azimuth = 73.90843°
backward_azimuth =254.46899°
distance = 38.16 NM, 70.66570km

Using geodesic calculator

	Line Definition
		Start Point: Latitude: N42:30:06.00000, Longitude: W37:00:06.00000
		  End Point: Latitude: N42:40:30.00000, Longitude: W36:10:24.00000
	Result:		     Pt1 to Pt2			Pt2 to Pt1
		        Azimuth: 73.90843			254.46899
		Reverse Azimuth: 254.46899			73.90843
			 Distance: 38.16 (nm)  70665.70 (m) 

See check using QGIS which provides the same value as the geodesic calculator

![image](https://user-images.githubusercontent.com/4627073/61770609-42896d80-ae20-11e9-82d9-3ed7f1242906.png)

**Comment by porosnie** [comment]
Corrected
