### ISSUE TITLE
NDBs missing EPSG information

### ISSUE THREAD

**Issue by antoniolocandro** [aixm/donlon#8]
Seems the only features in the dataset that have no EPSG information are NDB, honestly I can't determine if the EPSG for NDB are declared somewhere else as I'm not that skilled with the AIXM code itself. 

Here is one example

<aixm:location>
    <aixm:ElevatedPoint gml:id="epLLZ_OXS">
        <gml:pos>52.375583 -31.965222</gml:pos>
        <aixm:horizontalAccuracy xsi:nil="true" nilReason="unknown"/>
    </aixm:ElevatedPoint>
</aixm:location>

**Comment by antoniolocandro** [comment]
Based on the coding guidelines here https://ext.eurocontrol.int/aixm_confluence/display/public/ACG/Coordinate+Reference+System there are several rules for NDB SRS (EPSG) determination, however what would be the actual advantage over specifying always the SRS except the obvious size reduction. Seems that explicit SRS  is used in most GML samples from domains including INSPIRE GML examples https://inspire.ec.europa.eu/forum/file/view/107486/example-of-gml-file-conformant-to-inspire-land-cover-vector-application-schema

**Comment by porosnie** [comment]
Corrected
